// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

// user api

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Reg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reg) Reset()         { *m = Reg{} }
func (m *Reg) String() string { return proto.CompactTextString(m) }
func (*Reg) ProtoMessage()    {}
func (*Reg) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Reg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reg.Unmarshal(m, b)
}
func (m *Reg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reg.Marshal(b, m, deterministic)
}
func (m *Reg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reg.Merge(m, src)
}
func (m *Reg) XXX_Size() int {
	return xxx_messageInfo_Reg.Size(m)
}
func (m *Reg) XXX_DiscardUnknown() {
	xxx_messageInfo_Reg.DiscardUnknown(m)
}

var xxx_messageInfo_Reg proto.InternalMessageInfo

type Reg_Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reg_Request) Reset()         { *m = Reg_Request{} }
func (m *Reg_Request) String() string { return proto.CompactTextString(m) }
func (*Reg_Request) ProtoMessage()    {}
func (*Reg_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 0}
}

func (m *Reg_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reg_Request.Unmarshal(m, b)
}
func (m *Reg_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reg_Request.Marshal(b, m, deterministic)
}
func (m *Reg_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reg_Request.Merge(m, src)
}
func (m *Reg_Request) XXX_Size() int {
	return xxx_messageInfo_Reg_Request.Size(m)
}
func (m *Reg_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Reg_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Reg_Request proto.InternalMessageInfo

func (m *Reg_Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Reg_Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Reg_Request) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *Reg_Request) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Reg_Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reg_Response) Reset()         { *m = Reg_Response{} }
func (m *Reg_Response) String() string { return proto.CompactTextString(m) }
func (*Reg_Response) ProtoMessage()    {}
func (*Reg_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 1}
}

func (m *Reg_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reg_Response.Unmarshal(m, b)
}
func (m *Reg_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reg_Response.Marshal(b, m, deterministic)
}
func (m *Reg_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reg_Response.Merge(m, src)
}
func (m *Reg_Response) XXX_Size() int {
	return xxx_messageInfo_Reg_Response.Size(m)
}
func (m *Reg_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Reg_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Reg_Response proto.InternalMessageInfo

func (m *Reg_Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Login struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

type Login_Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_Request) Reset()         { *m = Login_Request{} }
func (m *Login_Request) String() string { return proto.CompactTextString(m) }
func (*Login_Request) ProtoMessage()    {}
func (*Login_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0}
}

func (m *Login_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_Request.Unmarshal(m, b)
}
func (m *Login_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_Request.Marshal(b, m, deterministic)
}
func (m *Login_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_Request.Merge(m, src)
}
func (m *Login_Request) XXX_Size() int {
	return xxx_messageInfo_Login_Request.Size(m)
}
func (m *Login_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Login_Request proto.InternalMessageInfo

func (m *Login_Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Login_Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Login_Request) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Login_Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_Response) Reset()         { *m = Login_Response{} }
func (m *Login_Response) String() string { return proto.CompactTextString(m) }
func (*Login_Response) ProtoMessage()    {}
func (*Login_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 1}
}

func (m *Login_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_Response.Unmarshal(m, b)
}
func (m *Login_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_Response.Marshal(b, m, deterministic)
}
func (m *Login_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_Response.Merge(m, src)
}
func (m *Login_Response) XXX_Size() int {
	return xxx_messageInfo_Login_Response.Size(m)
}
func (m *Login_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Login_Response proto.InternalMessageInfo

func (m *Login_Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Reg)(nil), "user.Reg")
	proto.RegisterType((*Reg_Request)(nil), "user.Reg.Request")
	proto.RegisterType((*Reg_Response)(nil), "user.Reg.Response")
	proto.RegisterType((*Login)(nil), "user.Login")
	proto.RegisterType((*Login_Request)(nil), "user.Login.Request")
	proto.RegisterType((*Login_Response)(nil), "user.Login.Response")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x1a, 0x18, 0xb9, 0x98, 0x83,
	0x52, 0xd3, 0xa5, 0xa2, 0xb9, 0xd8, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x11,
	0x2e, 0xd6, 0x82, 0x8c, 0xfc, 0xbc, 0x54, 0x09, 0x26, 0xb0, 0x20, 0x84, 0x23, 0x24, 0xc0, 0xc5,
	0x5c, 0x50, 0x9e, 0x22, 0xc1, 0x0c, 0x16, 0x03, 0x31, 0x41, 0xea, 0x52, 0x73, 0x13, 0x33, 0x73,
	0x24, 0x58, 0x20, 0xea, 0xc0, 0x1c, 0x29, 0x19, 0x2e, 0x8e, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc,
	0x62, 0xb0, 0x9e, 0xdc, 0xe2, 0x74, 0xa8, 0xe1, 0x20, 0xa6, 0x52, 0x0e, 0x17, 0xab, 0x4f, 0x7e,
	0x7a, 0x66, 0x9e, 0x94, 0x2b, 0x55, 0xdc, 0x80, 0xdf, 0x36, 0xa3, 0x0c, 0x2e, 0x96, 0xd0, 0xe2,
	0xd4, 0x22, 0x21, 0x1d, 0xb0, 0xbf, 0x85, 0x04, 0xf5, 0xc0, 0x41, 0x12, 0x94, 0x9a, 0xae, 0x07,
	0xb5, 0x5b, 0x4a, 0x08, 0x59, 0x08, 0x6a, 0x8e, 0x11, 0xd4, 0x8d, 0x42, 0xc2, 0x10, 0x49, 0x30,
	0x07, 0xae, 0x43, 0x04, 0x55, 0x10, 0xa2, 0xc7, 0x89, 0x3f, 0x8a, 0x37, 0xb1, 0x20, 0x53, 0x1f,
	0x24, 0x65, 0x0d, 0x22, 0x92, 0xd8, 0xc0, 0x01, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x24,
	0x0b, 0x64, 0xf0, 0x86, 0x01, 0x00, 0x00,
}
